    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-12 indented-text">
            <h1>Learning the Dances</h1>
                <p>On the day of the ball, we teach a longer afternoon class, and also a 30 minute class right before the ball. You can also practice before the ball at the locations listed below.</p>
          <h2>Afternoon Dance Class - 3:00PM</h2>
          <p>On the afternoon of the ball, in the same location, there is a 2½ hour dance class taught by Tom Hill, Amelia Thomas and Hilary Powers.</p>
            <h3>The Dances</h3>
                <p>We'll be teaching the Waltz, Polka, Schottisch, Mazurka, Galop and the <a href="congress.html">Congress of Vienna Waltz</a></p>
                <p>Note that, as this is a Victorian Ball, we teach the Victorian form of the Waltz. Anyone who is familiar with other versions of the Waltz should have no difficulty learning the Victorian style in an afternoon.</P>
            <h3>Clothing & Footwear for the Class</h3>
          <p>Most people attend the class in street clothes, changing after the class for the ball.</p>
            <p>You will, of course, want your dance shoes for the class. Any shoe you can turn in, on a wooden floor will likely work. Avoid grippy athletic shoes, platforms and spike heels!</p>


            <h3>Price</h3>
            <p>The cost of the afternoon class is $10.</p>

          <h2 id="evening">Evening Dance Class - 6:45</h2>
          <p>This is a half-hour introduction to basic Waltz, Polka and Schottische.</p>
          <p>If you are new to dancing, we recommend the afternoon class, half an hour is a very short time in which to learn to dance.</p>
          <h1>Other Learning Options</h1>
          <ul>
                <li><a href="http://fridaynightwaltz.com">Friday Night Waltz</a>
                <li><a href="http://peersdance.org">Peers</a>
                <li><a href="http://eastbaywaltz.com">East Bay Waltz</a>
            </ul>
            <p>If you are not already a dancer, taking any couples dance class before the ball will help: swing, tango, etc.</p>
        <h1>Book</h1>
            <p>For a book on teaching dance, by the Gaskell Ball instructor, go <a href="http://www.howtoteachballroomdancing.com">here</a>.</p>
            <p>Note this is a book on teaching dance, not a book that teaches the dances from the ball.</p>
          
        </div>
        
      </div>

    </div> <!-- /container -->
