    <div class="container">
      <div class="row">
        <div class="col-md-12 indented-text">
            <h1 id="pageName">The Congress of Vienna Waltz</h1>
            <div class="feature">
                <p>The Congress of Vienna Waltz is a elegant and romantic choreographed waltz that is frequently
                danced at The Gaskell Ball.</p>
                <p>The dance takes its name from
                <a href="http://en.wikipedia.org/wiki/Congress_of_Vienna">The Congress of Vienna</a>, a political
                conference held in Vienna, Austria, in 1814 & 1815.</p>
                <p>The dance was choreographed by <a href="http://en.wikipedia.org/wiki/John_Hertz_%28fan%29">John Hertz</a>.
                The original version of the music can be found <a href="http://tibit.com/congress/">here</a>. There
                are also several covers of the music available, by</p>
                <ul>
                    <li><a href="http://www.brassworksband.com/recordings.html">The Brassworks Band</a>
                    <li><a href="http://www.well.com/~cwj/bangersandmash/BatF.html">Bangers and Mash</a>
                    <li><a href="http://itunes.apple.com/us/album/balls-in-your-face/id377568197">Lee Presson and the Nails</a>.
                </ul>
            </div>
        </div>

       </div>
      </div>

      <hr>

    </div> <!-- /container -->
