    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-12 indented-text">
          <h1>What to Wear</h1>

<p>The Gaskell Ball is a Formal Victorian Ball, and Victorian formalwear the preferred standard of dress. 
Formalwear of more recent years is also totally acceptable.</p>
<p>You can check the photo at the top of the page
to get an idea of what is typically worn at the ball.</p>
<p>The December, 2024 ball is <em>not</em> a costume ball.</p>

<p>To preserve the look of the ball, casual attire, such as Jeans and T-shirts, casual shirts, etc., will not be allowed.</p>
<p>No part of your attire that might be 
a hazard to other dancers is allowed. Weapons are not allowed, not even if they are historically accurate parts of your attire. Of course, </p>
<p>If you haven't danced in what you will be wearing, we recommend testing this before the ball.</p>
<p>The committee reserves the right to turn away anyone not appropriately attired.</p>

<h2>Gentlemen's Attire</h2>

<p>Tuxedos, of any year, are the most commen attire for gentlemen. </p>
<p>Historical formal attire is also popular, such as Tailcoats or Cutaways.</p>
<p>Hstorical military <em>dress</em> uniforms are also worn. (no swords).</p>
<p>Modern dress uniforms are also welcome, if they are yours.</p>
<p>A modern suit is acceptable, and a jacket & tie (with slacks & a dress shirt) is the minimum level of dress.</p>

<h2>Ladies' Attire</h2>

<p>Ladies' attire may include ballgowns, evening gowns or any formal dress. Prom dresses and bridesmaids dress can work, too.</p>
<p>When choosing your attire for the evening, such things as non-removable trains, exposed hat pins, or costume pieces that may poke or annoy other dancers should be avoided.</p>
<p>It is also rather challenging to dance in a dress that brushes the floor so try to leave at least 4 inches clearance.
Hem appropriately or you may be stepping on it all night.</p>

<h2>Shoes</h2>

<p>A ball is a great place to wear comfortable shoes. If you are wearing a long dress, no one will see your shoes, anyway.</p>
<p>Shoes designed for dancing are best, if you have them.</p>
<p>Shoes that can turn on a wooden floor are good. Most athletic shoes are not good, as they are designed to grip the floor. The really slick leather soled men's dress shoes aren't ideal, either, as they are too slippery.</p>
<p>Avoid tall platforms or spike heels, they are a danger both to yourself, and those around you.<p>

        </div>
        
      </div>

    </div> <!-- /container -->
