    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-12 indented-text">
          <h1>What to Wear</h1>

<p>The Gaskell Ball is a Formal Victorian Ball, and that is the preferred standard of dress. 
Formalwear of more recent years is acceptable.</p>

<p>To preserve the look of the ball, Jeans and T-shirts, casual shirts, etc., are not allowed.</p>
<p>Weapons are not allowed, not even if they are historically accurate parts of your attire.</p>

<p>If you haven't danced in what you will be wearing, we recommend testing this before the ball.</p>

<h2>Gentlemen</h2>

<p>
Tuxedos are the most commen attire for gentlemen. 
Historical formal attire is also popular, such as Tailcoats or Cutaways.
Hstorical military uniforms are also worn. (no swords)
Modern dress uniforms are also welcome, if they are yours. 
A modern suit is acceptable, and a jacket & tie (with slacks & a dress shirt) is the minimum level of dress.
</p>

<h2>Ladies</h2>

<p>Ladies' attire may include ballgowns, evening gowns or any formal dress. Prom dresses and bridesmaids dress can work, too.</p>
<p>
When choosing your attire for the evening, bear in mind that one goal of the evening is to dance in your attire. 
Such things as trains, or costume pieces that may poke or annoy other dancers should be avoided. 
It is also rather challenging to dance in a dress that brushes the floor so try to leave at least 4 inches clearance. 
Hem appropriately or you may be stepping on it all night!
</p>

<h2>Shoes</h2>

<p>A ball is a great place to wear comfortable shoes. If you are wearing a long dress, no one will see them!</p>
<p>Shoes designed for dancing are best, if you have them.</p>
<p>Athletic shoes are not good, as they are designed to grib the floor, and dancing requires turning</p>
<p>Avoid tall platforms or spike heels, they are a danger both to yourself, and those around you! Besides, if you are wearing a long dress, no one will see your shoes!<p>

        </div>
        
      </div>

    </div> <!-- /container -->
