    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-12 indented-text">
          <h1>What to Wear</h1>

<h2>Costumes</h2>
<p>The Halloween dance is a Formal Costume Ball. At a formal costume ball, standard formal dress is still accepted; costumes are admired, but not required. Historical costumes, modern costumeis, and future costumes are all welcome. Break out your favorite vintage attire, cosplay, or steampunk gear.</p>

<p>Costumes that may be a hazard to those around you will not be allowed. So make sure you don't have sharp parts, swinging parts or parts that people may trip over, etc. You'll probably want to dance in your costume, so we recommend testing this before the ball.</p>

<p>Note that standards of dress still apply: Jeans and T-shirts, casual shirts, etc., will not be allowed (not even if you say 'it's a costume!').</p>
<p>Weapons are not allowed, either, not even if they are historically accurate parts of your costume.</p>


<h2>Formal Attire</h2>
<h3>Gentlemen</h3>

<p>Tuxedos are probably the most commen attire for gentlemen. Historical formal attire is also popular, such as Tailcoats or Cutaways; Hstorical military uniforms are also worn. Modern dress uniforms are also welcome, if they are yours. A modern suit is quite acceptable, and a jacket & tie (with slacks & a dress shirt) is the minimum level of dress.</p>



<h3>Ladies</h3>

<p>Ladies' attire may include ballgowns, evening gowns or any formal dress. Prom dresses and bridesmaids dress can work, too. Steampunk formal is also appropriate, but not casual.</p>

<p>When choosing your attire for the evening, bear in mind that one goal of the evening is to dance in your costume. Such things as trains, or costume pieces that may poke or annoy other dancers should be avoided. It is also rather challenging to dance in a dress that brushes the floor so try to leave at least 4 inches clearance. Hem appropriately or you may be stepping on it all night!</p>
<h2>Shoes</h2>

<p>A ball is a great place to wear comfortable shoes. Avoid tall platforms or spike heels, they are a danger both to yourself, and those around you! Besides, if you are wearing a long dress, no one will see your shoes!<p>

          
        </div>
        
      </div>

    </div> <!-- /container -->
