<!-- Example row of columns -->
   <div class="row">
      <div class="col-md-8">
         <h2>Formal Events</h2>
         <p>There are many lovely formal events throughout the year. This is a brief list of some of them.</p>
      </div>
   </div>
   <div>
      <ul>
         <li><a href="https://www.artdecopreservationball.com/">Art Deco Preservation Ball</a></li>
         <li><a href="https://artdecola.org/avalon-ball-faq">The Avalon Ball</a> May 17, 2025, Catalina Island</li>
         <li><a href="https://www.fanime.com/events/#black-and-white-ball">Fanime Black and White Ball</a></li>
         <li><a href="https://www.fantastiquecollection.com/fantastique-starfall-balltm-2025-ca">Fantastique Starfall Ball™ 2025</a></li>
         <li><a href="https://www.hssv.org/give/more-ways-to-give/the-fur-ball/">Fur Ball (Humane Society)</a></li>
         <li><a href="http://gaskellball.com">Gaskell Ball</a></li>
         <li><a href="https://www.sfopera.com/seasons/opera-ball/">SF Opera Ball</a></li>
         <li><a href="https://www.sfwaltzingsociety.org/">SF Waltzing Society</a></li>
         <li><a href="https://victoriandance.org/">Social Daunce Irregulars</a> November, in Pasadena CA</li>
      </ul>
   </div>
</div>
<!-- /container -->
