    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>The Ball</h2>
          <p>The 2015 ball was a smash success, with hundreds in attendance. </p>
          <p>The next ball will be in 2024. Watch this space, or follow us on <a href="facebook.com/gaskellball">facebook</a>.</p>
          <p><a class="btn btn-default" href="upcomingevents.html" role="button">More Info &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Dance Classes</h2>
          <p>On the afternoon of the ball, in the same location, there is a 2 ½ hour beginner dance class. The class covers many of the dances that will be done at the ball.</p>
          <p><a class="btn btn-default" href="classes.html" role="button">More Info &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>What to Wear</h2>
          <p>The standard of dress is formal, that means dress up! 
            When choosing your attire for the evening, bear in mind that one goal of the evening is to dance in your costume.</p>
          <p><a class="btn btn-default" href="costumes.html" role="button">More Info &raquo;</a></p>
       </div>
      </div>
    </div> <!-- /container -->
