    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>The Ball</h2>
          <p>The next ball is our Halloween Gaskell's formal costume ball.</p>
          <p>Dress your finest, or your most creative - but dress to dance!</p>
          <p><a class="btn btn-default" href="upcomingevents.html" role="button">More Info &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Dance Class</h2>
          <p>On the afternoon of the ball, in the same location, there is a 2 ½ hour beginner dance class. The class covers many of the dances that will be done at the ball.</p>
          <p><a class="btn btn-default" href="classes.html" role="button">More Info &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>What to Wear</h2>
          <p>The standard of dress is formal, that means dress up! 
            When choosing your attire for the evening, bear in mind that one goal of the evening is to dance in your costume.</p>
          <p><a class="btn btn-default" href="costumes.html" role="button">More Info &raquo;</a></p>
       </div>
      </div>
    </div> <!-- /container -->
