    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-12 indented-text">
          <h2>Location</h2>

<p>Gaskell's is held at the <a href="http://oaklandscottishrite.com/">Oakland Scottish Rite Center</a>, 1547 Lakeside Dr. Oakland, CA, USA</p>
<iframe width="640" height="480" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=scottish+rite+oakland&amp;aq=&amp;sll=37.0625,-95.677068&amp;sspn=36.999937,72.070313&amp;vpsrc=6&amp;ie=UTF8&amp;hq=scottish+rite&amp;hnear=Oakland,+Alameda,+California&amp;t=m&amp;cid=8207516474646682173&amp;ll=37.811072,-122.260151&amp;spn=0.032549,0.054932&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=scottish+rite+oakland&amp;aq=&amp;sll=37.0625,-95.677068&amp;sspn=36.999937,72.070313&amp;vpsrc=6&amp;ie=UTF8&amp;hq=scottish+rite&amp;hnear=Oakland,+Alameda,+California&amp;t=m&amp;cid=8207516474646682173&amp;ll=37.811072,-122.260151&amp;spn=0.032549,0.054932&amp;z=14&amp;iwloc=A" style="color:#0000FF;text-align:left">View Larger Map</a></small>

<h2>Getting to the Ball</h2>
<p>Parking is limited in the area. Please consider Car Pools, Uber/Lyft, and Public Transportation.<p>
<p>If you are staying at a hotel, please park at the hotel and Uber/Lyft to the ball.</p>
<p>The ball is ending an hour earlier, 11pm, so you can finish the ball, and still easily make the last bart train</p>
<p>You can combine methods: Park at Rockridge, Bart to Oakland, Lyft to the hall.</p>
<p>If you have great strategy for getting to the ball, let us know.<p>
<h3>Parking</h3>
<p>This is some parking in the lot behind the hall, on Madison St., additional parking is available on the street.</p>
<p>There are a number of paid lots avaiable in the area, as well.</p>
        
          
        </div>
        
      </div>
    </div> <!-- /container -->
