    <!-- Fixed navbar -->
    <style>
    .tm {
        font-size: 0.5em;
        vertical-align: top;
        position: relative;
        top: -0.5em;
    }
    </style>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html">Gaskell<span class="tm">™</span> Ball</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="upcomingevents.html">Next Ball</a></li>
            <li><a href="classes.html">Classes</a></li>
            <li><a href="costumes.html">What to Wear</a></li>
            <li><a href="location.html">Location</a></li>
            <li><a href="http://facebook.com/gaskellball">Facebook</a></li>
            <li><a href="https://www.instagram.com/gaskellball/">Instagram</a></li>

          </ul>
<!--
          <ul class="nav navbar-nav navbar-right"  id="email_block">
           <!-- begin addlist-vr.htm  --     >
            <form method="post" action="http://oi.vresp.com?fid=ac47a82739" class="navbar-form navbar-left"
                target="vr_optin_popup" onsubmit="window.open( 'http://www.verticalresponse.com', 'vr_optin_popup', 'scrollbars=yes,width=600,height=450' ); return true;">
                Mailing list:
                <input name="email_address" placeholder="Email" size="15" style="margin-top: 5px; border: 1px solid #999; padding: 3px;"/>
                <input type="submit" value="Join" style="margin-top: 5px; border: 1px solid #999; padding: 3px;"/><br/>
            </form>
        <!-- end addlist-vr.htm  --   >
          </ul>
-->
        </div><!--/.nav-collapse -->
      </div>
    </nav>
