<div class="container">
   <!-- Example row of columns -->
   <div class="row">
      <div class="col-md-4">
         <h2>Press Information</h2>
         <p>The Gaskell Ball originated in Oakland, at Mills College, in 1979. It continued until 2015, and then took a hiatus.</p>
         <p>The next ball will be in 2024. Watch this space, or follow us on <a href="facebook.com/gaskellball">Facebook</a>.</p>
      </div>
      <br style="clear:both" />
      <br>
      <div>
         <hr>
         <a href="./images/DSC02547_busy_dance_level.jpeg" target="_blank">
         <img width=400 src="./images/DSC02547.jpeg">
         </a>
         <hr>
         <a href="./images/steph_eric2.jpeg" target="_blank">
         <img width=400 src="./images/steph_eric2.jpeg">
         </a>
         <hr>
        <a href="./images/DSC04016.jpeg" target="_blank">
         <img width=400 src="./images/DSC04016.jpeg">
         </a>
         <hr>
         <a href="./images/DSC03100.jpeg" target="_blank">
         <img width=400 src="./images/DSC03100.jpeg">
         </a>
         <hr>
         <a href="./images/chris.jpeg" target="_blank">
         <img width=400 src="images/chris.jpeg">
         </a>
         <hr>
         <a href="./images/DSC02630.jpeg" target="_blank">
         <img width=400 src="./images/DSC02630.jpeg">
         </a>
         <hr>
         <a href="./images/DSC02692.jpeg" target="_blank">
         <img width=800 src="./images/DSC02692.jpeg">
         </a>
         <hr>
         <a href="./images/DSC04028.jpeg" target="_blank">
         <img width=400 src="./images/DSC04028.jpeg">
         </a>
         <hr>
         <a href="./images/lauren_jesse.jpeg" target="_blank">
         <img width=400 src="./images/lauren_jesse.jpeg">
         </a>
         <hr>
         <a href="./images/DSC03828.jpeg" target="_blank">
         <img width=400 src="./images/DSC03828.jpeg">
         </a>
         <hr>
         <a href="./images/DSC03393.jpeg" target="_blank">
         <img width=400 src="./images/DSC03393.jpeg">
         </a>
      </div>
   </div>
</div> <!-- /container -->
