    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Press Information</h2>
          <p>The Gaskell Ball originated in Oakland, at Mills College, in 1979. It continued until 2015, and then took a hiatus.</p>
          <p>The next ball will be in 2024. Watch this space, or follow us on <a href="facebook.com/gaskellball">Facebook</a>.</p>
       </div>
<br style="clear:both" />
<br>
       <div>
<hr>
          <img width=400 src="./images/DSC02547.jpeg">
<hr>
          <img width=400 src="./images/steph_eric2.jpeg">
<hr>
          <img width=400 src="./images/DSC04016.jpeg">
<hr>
          <img width=400 src="./images/DSC03100.jpeg">
<hr>
          <img width=400 src="images/chris.jpeg">
<hr>
          <img width=400 src="./images/DSC02630.jpeg">
<hr>
          <img width=800 src="./images/DSC02692.jpeg">
<hr>
          <img width=400 src="./images/DSC04028.jpeg">
<hr>
          <img width=400 src="./images/lauren_jesse.jpeg">
<hr>
          <img width=400 src="./images/DSC03828.jpeg">
<hr>
          <img width=400 src="./images/DSC03393.jpeg">
       </div>
      </div>
    </div> <!-- /container -->
