    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-12 indented-text">

<h2>The Next Gaskell Ball: Dec 28th, 2024</h2>
<!--a href="https://squareup.com/market/ye-gaskell-occasional-dance-society/admission-to-the-october-th-gaskell-ball-1" class="btn btn-info" role="button">Buy Tickets Now & Save!</a-->
<p/>
<p>The Gaskell Ball is returning!</p>
<!-- <p>If you are interested in actually working to make this happen, reach out to us.</p> -->
<p>This was last updated 2024-07-19</p>

<!-- <p>Costumes can include historical costumes, modern formal wear, fictional characters, cosplay, steampunk and more. Be elegant Be dramatic. Be outrageous! Please check our <a href="costumes.html">What to Wear</a> page for more information</p> -->

<H3>Music</H3>
<p>Live music will be provided by the <a href="http://www.brassworksband.com/">Brassworks Band.</a></p>

<H3>Location</H3>
<p>The ball will be held at the Oakland Scottish Rite Center, 1547 Lakeside Dr. Oakland, CA, USA</p>
<a href="location.html" class="btn btn-info" role="button">Map</a>

<h3>Schedule</h3>
<p><em>This schedule may change. Please check again, closer to the date of the ball</em></p>
<dl class="dl-horizontal">
    <dt>3:00pm</dt><dd><a href="classes.html">Afternoon Dance Class</a> (until 6:00pm)<dd>
    <dt>6:30pm</dt><dd> Doors open for the ball<dd>
    <dt>6:40pm</dt><dd><a href="classes.html#evening">Brief dance class/review</a><dd>
    <dt>7:30pm</dt><dd> Dancing begins<dd>
    <dt>11:00</dt><dd> The ball ends<dd>
</dl>

<h3>Admission</h3>
Ticket prices for 2024 TBD
<!--
<p><a href="https://squareup.com/market/ye-gaskell-occasional-dance-society/admission-to-the-october-th-gaskell-ball-1">$20 in advance.</a></p>
<p>$25 at the door.</p>
-->


        </div>
        
      </div>

      <hr>

      <div id="footer">
      </div>
    </div> <!-- /container -->
